import Head from 'next/head'

export default function Loading() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <p>Loading...</p>
      </div>
    </>
  )
}
