//import {useState} from 'react'

import Head from 'next/head'

import Posts from '../../../components/first/Posts'
import PostInput from '../../../components/first/PostInput'

import { Suspense } from 'react'
import Loading from '../loading'

export default async function FirstPage({
  params,
  searchParams,
}: {
  params: { slug: string }
  searchParams?: { [key: string]: string | string[] | undefined }
}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="flex-1">
        <div className="flex flex-col justify-center sm:w-3/4  lg:w-4/5 xl:w-3/5 mx-auto py-3 px-2">
          <PostInput />
          <Suspense fallback={<Loading />}>
            {/* @ts-expect-error Async Server Component */}
            <Posts params={params} searchParams={searchParams} />
          </Suspense>
        </div>
      </section>
    </>
  )
}
