import Head from 'next/head'
import LogingForm from './(components)/LogingForm'

export default function Login() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LogingForm />
    </>
  )
}
