//import {useState} from 'react'

import Head from 'next/head'
import Image from 'next/image'
import Posts from './components/Posts'
import { users, posts, comments } from './data.js'

interface Iuser {
  id: number
  userName: string
  position: string
  image: string
}

interface Ipost {
  id: number
  owner: number
  text: string
  image: string
  likes: number[]
}

interface Icomments {
  id: number
  text: string
  post: number
  user: number
  parent?: number
}

const initialUsers: Iuser[] = users
const initialComments: Icomments[] = comments
const initialPosts: Ipost[] = posts

export default function FirstPage() {
  // const theUsers: Iuser[] = users
  // const thePosts: Ipost[] = posts
  // const theComments: Icomments[] = comments
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="flex flex-col justify-center sm:w-3/4  lg:w-1/2 xl:w-2/6 mx-auto py-3">
        <Posts />
      </section>
    </>
  )
}
