import Head from 'next/head'
import Image from 'next/image'

export default function FirstPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="flex flex-col justify-center sm:w-3/4  lg:w-1/2 xl:w-2/6 mx-auto py-3">
        <div>
          <div className="border-solid border-2 border-gray-500 rounded-lg">
            <div className="flex p-2">
              <div className="object-cover">
                <Image
                  className="rounded-full"
                  src="https://i.pravatar.cc/100"
                  alt="avatar"
                  width={50}
                  height={50}
                />
              </div>

              <div className="flex flex-col justify-around flex-1 px-5">
                <div>
                  <h2 className="text-xl font-bold">Some name</h2>
                </div>
                <div>
                  <p className="text-lg">some description</p>
                </div>
              </div>
              <div className="text-4xl">...</div>
            </div>
            <div className="p-2">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla
              tempora fugiat expedita deleniti architecto iusto corrupti nam,
              odit unde! Nihil.
            </div>
            <div className="object-cover">
              <Image
                className="w-full"
                src="https://i.pravatar.cc/800"
                width={400}
                height={400}
                alt="some Image"
              />
            </div>
            <div className="px-2">
              <div className="flex py-4 px-2 text-slate-400">
                <div>
                  <span>230</span> Likes
                </div>
                <div className="flex-1 text-right text-slate-400">
                  <span>5</span>Comentarios
                </div>
              </div>
              {/* Coments & Like buttons */}
              <div className="flex border-t-2 border-solid border-slate-500 p-1">
                <div className="flex-1">
                  <button className="w-full py-4 rounded-lg text-slate-400 hover:bg-slate-500 hover:text-slate-200">
                    Me Gusta
                  </button>
                </div>
                <div className="flex-1">
                  <button className="w-full py-4 rounded-lg text-slate-400 hover:bg-slate-500 hover:text-slate-200 ">
                    Comentar
                  </button>
                </div>
              </div>
              {/* coments */}
              <div className="border-t-2 border-solid border-slate-500 px-1 py-2">
                {/* coment */}
                <div className="flex gap-2 p-1">
                  <div className="object-cover">
                    <Image
                      className="rounded-full"
                      src="https://i.pravatar.cc/100"
                      alt="avatar small"
                      width={70}
                      height={70}
                    />
                  </div>
                  <div>
                    <div className="bg-slate-500 rounded-2xl p-2">
                      <h5 className="text-base font-bold text-slate-200">
                        Comment name
                      </h5>
                      <p className="text-slate-200">
                        Lorem, ipsum dolor sit amet consectetur adipisicing
                        elit. Deleniti nam temporibus neque corporis beatae
                        voluptatibus !
                      </p>
                    </div>
                    <div className="px-3">
                      <span className="text-slate-400">responder</span>
                    </div>
                  </div>
                </div>
                {/* another comment */}
                <div className="flex gap-2 py-1 ml-16">
                  <div className="object-cover">
                    <Image
                      className="rounded-full"
                      src="https://i.pravatar.cc/100"
                      alt="avatar small"
                      width={70}
                      height={70}
                    />
                  </div>
                  <div>
                    <div className="bg-slate-500 rounded-2xl p-2">
                      <h5 className="text-base font-bold text-slate-200">
                        Comment name
                      </h5>
                      <p className="text-slate-200">
                        Lorem, ipsum dolor sit amet consectetur adipisicing
                        elit. Deleniti nam temporibus neque corporis beatae
                        voluptatibus !
                      </p>
                    </div>
                    <div className="px-3">
                      <span className="text-slate-400">responder</span>
                    </div>
                  </div>
                </div>
                <div className="flex gap-2 p-1">
                  <div className="object-cover">
                    <Image
                      className="rounded-full"
                      src="https://i.pravatar.cc/100"
                      alt="avatar small"
                      width={70}
                      height={70}
                    />
                  </div>
                  <div>
                    <div className="bg-slate-500 rounded-2xl p-2">
                      <h5 className="text-base font-bold text-slate-200">
                        Comment name
                      </h5>
                      <p className="text-slate-200">
                        Lorem, ipsum dolor sit amet consectetur adipisicing
                        elit. Deleniti nam temporibus neque corporis beatae
                        voluptatibus !
                      </p>
                    </div>
                    <div className="px-3">
                      <span className="text-slate-400">responder</span>
                    </div>
                  </div>
                </div>
                {/* comment imput */}
                <div className="flex gap-2 p-1 items-center border-t-2 border-slate-500 border-solid py-3">
                  <div className="object-cover">
                    <Image
                      className="rounded-full"
                      src="https://i.pravatar.cc/100"
                      alt="avatar small"
                      width={70}
                      height={70}
                    />
                  </div>
                  <form className="w-full">
                    <input
                      className="w-full p-2 rounded-xl bg-slate-500"
                      type="text"
                      placeholder="what do u think"
                    />
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}
